
document.write("<div >");
      document.write("<div class='col colIndent'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../../../ui/images/key.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='../../home/footer/inCyyte_top_polls_v1_top_polls.html'>Top Polls</a> </li>");
          document.write("<li> <a href='../../home/footer/inCyyte_search_results_v2.html'>Search Questions</a> </li>");
          document.write("<li> <a href='#'>Search Petitions</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div class='col colIndent'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../../../ui/images/signal.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='#'>Take The Tour</a> </li>");
          document.write("<li> <a href='../../home/footer/what_is_inCyyte.html'>What is inCyyte?</a> </li>");
          document.write("<li> <a href='#'>inCyyte For Business</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div class='col colIndent'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../../../ui/images/circle.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='../../home/footer/anonymity_and_inCyyte_v3_anonymity_and_inCyyte.html'>Anonimity  &amp; inCyyte</a> </li>");
          document.write("<li> <a href='../../home/footer/inCyyte_red_card_system_v1_red_card_system.html'>The Red Card System</a> </li>");
          document.write("<li> <a href='../../home/footer/faq_page_v3.html'>FAQs</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div class='col'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../../../ui/images/book.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='#'>Terms &amp; Conditions</a> </li>");
          document.write("<li> <a href='../../home/footer/inCyyte_privacy_policy_v2.html'>Privacy Policy</a> </li>");
          document.write("<li> <a href='../../home/footer/inCyyte_contact_us_v1.html'>Contact Us</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div style=' text-align:center; margin:140px 0 0 0; padding:0; color:#A4ACB2;'> &copy; inCyyte 2012 All rights reserved ");
	document.write("</div>");
    document.write("</div>");