
document.write("<div >");
      document.write("<div class='col colIndent'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../ui/images/key.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='#'>Top Polls</a> </li>");
          document.write("<li> <a href='#'>Search Questions</a> </li>");
          document.write("<li> <a href='#'>Search Petitions</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div class='col colIndent'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../ui/images/signal.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='#'>Take The Tour</a> </li>");
          document.write("<li> <a href='#'>What is inCyyte?</a> </li>");
          document.write("<li> <a href='#'>inCyyte For BUsiness</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div class='col colIndent'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../ui/images/circle.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='#'>Anonimity  &amp; inCyyte</a> </li>");
          document.write("<li> <a href='#'>The Red Card System</a> </li>");
          document.write("<li> <a href='#'>FAQs</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div class='col'>");
        document.write("<ul class='listWithMarker'>");
          document.write("<li> <a href='#'><img src='../ui/images/book.png' style='padding-bottom:12px;'></a> </li>");
          document.write("<li> <a href='#'>Terms &amp; Conditions</a> </li>");
          document.write("<li> <a href='#'>Privacy Policy</a> </li>");
          document.write("<li> <a href='#'>Contact Us</a> </li>");
        document.write("</ul>");
      document.write("</div>");
      document.write("<div style=' text-align:center; margin:140px 0 0 0; padding:0; color:#A4ACB2;'> &copy; inCyyte 2012 All rights reserved - Website created by Alight <img src='../ui/images/alight_logo.png' align='middle' style='padding-top:4px;'> ");
	document.write("</div>");
    document.write("</div>");